### ISSUE TITLE
Pump frequently switching on/off for 1 second for about an hour around 01:00 hrs every day

### ISSUE THREAD

**Issue by davidoff62** [jeroenvdwaal/underfloor_heating_pump_controller#1]
Seems like the anti-corrosion functions does something strange. At 0100 hrs the pump switches on and off every second for around an hour. It looks to me that something strange happens in the calculation if the anti corrosion should run or not....

![Pompje](https://user-images.githubusercontent.com/98104580/152333051-26fc3fb2-9eb1-4ada-bd86-04992f24fd7c.png)

**Comment by jeroenvdwaal** [comment]
Hi @davidoff62, yes, thank you for the feedback. This got the same message from another user. And I don't know yet what is happening. This switching is not good for the pump, so don't use the switch for now. One way of dealing with this is to disable the corrosion run inside the ESP Home script until it is fixed. 

You could help me out, finding the cause if you like. I could create an updated script with some additional logging. Let me know if you like help.

**Comment by davidoff62** [comment]
Hi Jeroen, 

Altough my guess is that you are a Dutch native speaker (so am I), let's stick to English so the world can follow. 

Of course i like to help, no doubt on that! I'm an electrical engineer, so software isn't really my thing (a.k.a. i'm learning), but uploading a modified script is well within my capabilities.

In the mean time some more info: i checked and crosschecked the availability of the NTP server server for the SonOFF (as my tought was that this could be of importance), this is the case. 

In your screenshot it clearly shows a continued operation of the pump :) but not at around 01:00 hrs, is this also normal behavior? .... from the documentaion i understood that if the pump did not run in the last 24 hrs because of high water temp the pump will run for 10 min at 01:00 local time (hence the NTP service). 

BR David

**Comment by jeroenvdwaal** [comment]
@davidoff62 Yes, you guessed right, I am a Dutch native speaker. And, yes, we should stick to English, so others can follow the discussion. I studied electrical engineering as well, but my career headed quite fast in the direction of software development. So I did a second study on software engineering. Both worlds are very interesting and are quite connected.

Nice that you like to cooperate! Let's see if we can fix the bug.

By the way, the problem you mention is reported earlier, see this conversation: https://community.home-assistant.io/t/diy-underfloor-heating-pump-controller-in-home-assistant/362954 

Are you using the S20 or the S26? 

In response to your remarks. 

> In the mean time some more info: i checked and crosschecked the availability of the NTP server server for the SonOFF (as my tought was that this could be of importance), this is the case.

Yes, I think that something goes wrong with the SNTP section. In the discussion on the home assistant forum, Martin removed the entire section of the corrosion run and moved that to an HA automation. Of course, this solves the problem, but the general idea was to have a 'stand-alone' solution, which could work without HA being online.

> In your screenshot it clearly shows a continued operation of the pump :) but not at around 01:00 hrs, is this also normal behavior?

![sensor_and_water_temperature](https://user-images.githubusercontent.com/47793670/152951017-c3e7651c-afb0-4c76-bb90-40160013713b.png)

The pump runs when warm water enters. There is a very small spike at one o'clock. That is only one minute. And that's indeed why the NTP service is configured for.

**Comment by davidoff62** [comment]
@jeroenvdwaal 

I'm using the S26

**Comment by davidoff62** [comment]
Thinking of this code; 
If the above is the issue, could the following be a solution?

```
time:
  - platform: sntp
    servers:  [172.16.10.1]
    on_time:
      # schedule anti corrosion action, once a day
      - hours: 1
        then:
          - globals.set:
              id: g_pump_demand_anti_corr
              value: "true"
          - script.execute: controller
       
      - hours: 1 minute: 2
        then:
          - globals.set:
              id: g_pump_demand_anti_corr
              value: "false"
          - script.execute: controller
```

**Comment by davidoff62** [comment]
Last night the pump did't freak out :) So i guess we can conclude the bug is in the above passage. Does my proposal makes sense? probably the syntax is faulty, but you get the point.....
![pompje](https://user-images.githubusercontent.com/98104580/153177433-8299f96f-c2a5-4b62-b7e9-795a5479c60b.png)

**Comment by jeroenvdwaal** [comment]
That's great to hear. Great that you changed the script successfully!! I'm curious if the servers: line is still needed, or does it work fine without? Could you check that?

**Comment by davidoff62** [comment]
Just checked without the servers: line. The automation does not work without the line, best is to keep it in i guess.....

Like said: i'm not a software guy, can you therefore explain why in your revised code you use - before hour, minutes and seconds? i only use it at the first line of the time definition (conform the example:  [https://esphome.io/components/time.html](url)

I feel confident now and i connected the pump. Tonight we'll (hopefully) see the code in action :)

**Comment by jeroenvdwaal** [comment]
I have one option in my sleeve to fix it in a more easy way. It is not important to run the anti-corrosion at one o'clock. A minute every 24 hours, approximately suffices. So instead of using the time section, I just create a loop, which just waits 24 hours and runs for a minute. Which could be any time of the day. Which is fine by this automation. What do you think about that approach?

**Comment by davidoff62** [comment]
@jeroenvdwaal 
Hi Jeroen, 

Thanks for the addition! i guess we have two flafours now;

1: you latest version making sure the pump runs at least once every 24hrs on a undifined time and does not need a NTP server.
2: my version that runs on a pre-defined time, but does need a reachable NTP server.

As a response to your latest remark:
I do run my own NTP server within my IoT network segment. In this way hosts in this network can be (and are!) separated from the internet, but still have access to a NTP server. That's the reason you only see a local IP in my code. 
I would like to run the pump at a pre defined time because my pump makes noise (and thus i run it at 10:00, not disburbing my sleep). Im my use case, i'll stick to flavour 2.......in other cases flavour 1 might be more practical!

**Comment by jeroenvdwaal** [comment]
Hi @davidoff62,

I am sorry for my late response. I posted something earlier, but I think didn't hit the submit button. It's nice to know that there is a preference for running it at a specific point in time. Thanks for the valuable feedback. I have only one question to ask. 

```yaml
  time:
  - platform: sntp
    on_time:
      # schedule anti corrosion action, once a day
      - hours: 1
        minutes: 0
        seconds: 0
        then:
          - globals.set:
              id: g_pump_demand_anti_corr
              value: "true"
          - script.execute: controller
          - delay: 60s
          - globals.set:
              id: g_pump_demand_anti_corr
              value: "false"
          - script.execute: controller
```
Did you test the script above? Do the minute and second entries solve the issue?
